### ISSUE TITLE
[Question] When I add .krew.yaml to my project the github action run error

### ISSUE THREAD

**Issue by hantmac** [kubernetes-sigs/krew-index#1977]
Hi, sorry to bother and I has a problem when adding the `.krew.yaml` to [this krew plugin](https://github.com/openkruise/kruise-tools) ,the github action run failed ,and I have add this plugin to krew index in [this pr](https://github.com/kubernetes-sigs/krew-index/pull/1809). 
The error is as flows:
![image](https://user-images.githubusercontent.com/7600925/152778499-579eb54d-624f-4f29-8625-4c3b54a40981.png)

Do you have any idea to solve this problem? Than you very much!

**Comment by rajatjindal** [comment]
`upload-sha256sums-plugin:` action does not have a checkout step, so it most likely dont have access to .krew file there.

just curious, is there any specific reason why you have implemented all steps of compiling/uploading etc as different steps instead of using something like `go-releaser` which takes care of most of these steps automatically?

**Comment by hantmac** [comment]
> `upload-sha256sums-plugin:` action does not have a checkout step, so it most likely dont have access to .krew file there.
> 
> just curious, is there any specific reason why you have implemented all steps of compiling/uploading etc as different steps instead of using something like `go-releaser` which takes care of most of these steps automatically?

Thank you very much, I forget to have a checkout step. But when I add the checkout step to release.yaml, I got another error.
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/7600925/153165325-23b04360-926c-4361-8927-ef543bd07afd.png">

The .krew.yaml file as flows:
```yaml
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kruise
spec:
  version: "{{ .TagName }}"
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha https://github.com/openkruise/kruise-tools/releases/download/{{ .TagName }}/kubectl-kruise-linux-amd64.tar.gz .TagName }}
      files:
        - from: "*/kubectl-kruise"
          to: "."
        - from: "*/LICENSE"
          to: "."
      bin: "kubectl-kruise"
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha https://github.com/openkruise/kruise-tools/releases/download/{{ .TagName }}/kubectl-kruise-linux-arm64.tar.gz .TagName }}
      files:
        - from: "*/kubectl-kruise"
          to: "."
        - from: "*/LICENSE"
          to: "."
      bin: "kubectl-kruise"
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha https://github.com/openkruise/kruise-tools/releases/download/{{ .TagName }}/kubectl-kruise-darwin-amd64.tar.gz .TagName }}
      files:
        - from: "*/kubectl-kruise"
          to: "."
        - from: "*/LICENSE"
          to: "."
      bin: "kubectl-kruise"
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha https://github.com/openkruise/kruise-tools/releases/download/{{ .TagName }}/kubectl-kruise-darwin-arm64.tar.gz .TagName }}
      files:
        - from: "*/kubectl-kruise"
          to: "."
        - from: "*/LICENSE"
          to: "."
      bin: "kubectl-kruise"
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha https://github.com/openkruise/kruise-tools/releases/download/{{ .TagName }}/kubectl-kruise-windows-amd64.tar.gz .TagName }}
      files:
        - from: "*/kubectl-kruise"
          to: "."
        - from: "*/LICENSE"
          to: "."
      bin: "kubectl-kruise"
  shortDescription: Easily handle OpenKruise workloads
  homepage: https://openkruise.io/
  description: |
    kubectl kruise is a kubectl plugin from the OpenKruise project. OpenKruise is an extended component suite for Kubernetes,
    which mainly focuses on application automations, such as deployment, upgrade, ops and avalibility protection.
    This plugin allows you to better handle, manage and maintain OpenKruise workloads.
```
