### ISSUE TITLE
in arm64 kubectl krew install score install as amd64 program

### ISSUE THREAD

**Issue by ufwtlsb** [kubernetes-sigs/krew-index#3875]
maybe config is error 
```
    - selector:
        matchLabels:
          os: linux
      uri: https://github.com/zegl/kube-score/releases/download/v1.18.0/kube-score_1.18.0_linux_amd64.tar.gz
      sha256: 2f4c3a43045ac4006fa1adcf970660828d2df09c4e9165bafe27d36479fa355a
      files:
        - from: "kube-score"
          to: .
        - from: "LICENSE"
          to: .
      bin: kube-score
```
